In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Datasets/student_multiple_features.csv")
df.head()

  Student  StudyHours Attendance  PreviousMarks  FinalMarks
0   Aarav           2         70           38.0          42
1    Sita           3         75           45.0          50
2     Ram           4         80           52.0          58
3  Anisha           5         85           60.0          68
4   Rohan           6         90           68.0          78

In [3]:
df.shape

(20, 5)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student        20 non-null     str
 1   StudyHours     20 non-null     int64
 2   Attendance     20 non-null     str
 3   PreviousMarks  19 non-null     float64
 4   FinalMarks     20 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 932.0 bytes

In [5]:
df['Attendance']

0         70
1         75
2         80
3         85
4         90
5         92
6         95
7         78
8         82
9         88
10        91
11        96
12        72
13        98
14        86
15    Absent
16        79
17        90
18        97
19        84
Name: Attendance, dtype: str

In [7]:
df['Attendance'] = pd.to_numeric(df['Attendance'], errors = "coerce")
df['Attendance']

0     70.0
1     75.0
2     80.0
3     85.0
4     90.0
5     92.0
6     95.0
7     78.0
8     82.0
9     88.0
10    91.0
11    96.0
12    72.0
13    98.0
14    86.0
15     NaN
16    79.0
17    90.0
18    97.0
19    84.0
Name: Attendance, dtype: float64

In [17]:
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())
df['Attendance']

0     70.000000
1     75.000000
2     80.000000
3     85.000000
4     90.000000
5     92.000000
6     95.000000
7     78.000000
8     82.000000
9     88.000000
10    91.000000
11    96.000000
12    72.000000
13    98.000000
14    86.000000
15    85.684211
16    79.000000
17    90.000000
18    97.000000
19    84.000000
Name: Attendance, dtype: float64

In [10]:
df.isnull().sum()

Student          0
StudyHours       0
Attendance       0
PreviousMarks    1
FinalMarks       0
dtype: int64

In [11]:
df['PreviousMarks'] = df['PreviousMarks'].fillna(df['PreviousMarks'].median())
df

   Student  StudyHours  Attendance  PreviousMarks  FinalMarks
0    Aarav           2   70.000000           38.0          42
1     Sita           3   75.000000           45.0          50
2      Ram           4   80.000000           52.0          58
3   Anisha           5   85.000000           60.0          68
4    Rohan           6   90.000000           68.0          78
5    Priya           7   92.000000           75.0          85
6    Kiran           8   95.000000           82.0          92
7    Nabin           4   78.000000           55.0          60
8    Suman           5   82.000000           63.0          70
9   Alisha           6   88.000000           70.0          79
10  Bikash           7   91.000000           78.0          87
11  Sabina           8   96.000000           85.0          95
12  Roshan           3   72.000000           48.0          52
13    Puja           9   98.000000           90.0          98
14  Manish           5   86.000000           66.0          73
15  Aakash           6   85.684211           72.0          81
16    Rita           4   79.000000           58.0          61
17   Deepa           7   90.000000           66.0          89
18  Sanjay           8   97.000000           88.0          96
19  Kushal           5   84.000000           64.0          74

In [12]:
df.isnull().sum()

Student          0
StudyHours       0
Attendance       0
PreviousMarks    0
FinalMarks       0
dtype: int64

In [23]:
# Features, Label
X = df[
    ['StudyHours', 'Attendance', 'PreviousMarks']
    ]
y = df['FinalMarks']


#convert to numpy array
X = X.to_numpy()
y = y.to_numpy()

#Split(Training, Testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#pick a model and give data to train it
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [24]:
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [0.46955086 0.54710982 0.73989409]
Intercept: -24.726565343333647

In [26]:
new_students = np.array([
    [10,80,60]
])

prediction = model.predict(new_students)
prediction

array([68.13137412])